on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: 2. Setup State Storage
jobs:
  bicep-provision-state-storage:
    steps:
        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          deploymentMode: Incremental
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./provision/statestore.bicep
          parameters: ./provision/storage.parameters.json
          failOnStdErr: false
