on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: 7. Setup Container App Order Processor
jobs:
  bicep-provision-environment:
    steps:
        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          deploymentMode: Incremental
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./src/services/order-processor/provision/service.bicep
          parameters: ./src/services/order-processor/provision/service.parameters.json
          failOnStdErr: false
