on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: 8. Setup Container App Checkout
jobs:
  bicep-provision-checkout-container-app:
    steps:
        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          deploymentMode: Incremental
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./src/services/checkout/provision/service.bicep
          parameters: ./src/services/checkout/provision/service.parameters.json
          failOnStdErr: false
