on:
  workflow_dispatch:
    branches:
      - main
name: 3. Setup PubSub Service Bus
jobs:
  bicep-deploy-pubsub-service-bus:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          deploymentMode: Incremental
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./provision/pubsub.bicep
          parameters: ./provision/pubsub.parameters.json
          failOnStdErr: false
