on:
  workflow_dispatch:
    inputs:
      updateRevision:
        type: boolean
        description: update container apps revision
    branches:
      - main
  # push:
  #   inputs:
  #     updateRevision:
  #       type: boolean
  #       description: update container apps revision
  #       default: true
  #   branches:
  #     - main
  #   paths:
  #     - src/services/order-processor/**
name: 6. order processor service containerization

jobs:
    build-and-push-container-order-processor:
        runs-on: ubuntu-latest
        env:
          containerName: order
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            cd src/services/order-processor
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.containerName }}:${{ github.sha }}
            docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.containerName }}:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.containerName }}:latest
            # docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.containerName }}:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.containerName }}:latest
        - name: Azure CLI script
          if: github.event.inputs.updateRevision == 'true'
          uses: azure/CLI@v1
          with:
            inlineScript: |
              az config set extension.use_dynamic_install=yes_without_prompt
              #az containerapp update --name orderprocessorapp --resource-group ${{ secrets.AZURE_RG }} --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.containerName }}:latest
              az containerapp revision restart --revision orderprocessorapp--3l0kxv8 --resource-group ${{ secrets.AZURE_RG }}
        # - name: 'Deploy to Azure Container Instances'
        #   uses: 'azure/aci-deploy@v1'
        #   with:
        #     resource-group: ${{ secrets.AZURE_RG }}
        #     dns-name-label: ${{ secrets.AZURE_RG }}${{ github.run_number }}
        #     image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.containerName }}:${{ github.sha }}
        #     registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
        #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        #     name: aci-${{ env.containerName }}
        #     location: 'west europe'