on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
permissions:
  id-token: write
  contents: read  
name: Deploy Environment
jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    steps: 
      - name: OIDC Login to Azure Public Cloud with AzPowershell (enableAzPSSession true)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
          enable-AzPSSession: true
      - name: deploy aca
        run: |
          az deployment group create --mode Incremental --resource-group ${{ secrets.AZURE_RG }} --template-file ./provision/environment.bicep --parameters: ./provision/environment.parameters.json
      - name: deploy state storage
        run: |
          az deployment group create --mode Incremental --resource-group ${{ secrets.AZURE_RG }} --template-file ./provision/statestore.bicep --parameters: ./provision/storage.parameters.json
      - name: deploy pubsub
        run: |
          az deployment group create --mode Incremental --resource-group ${{ secrets.AZURE_RG }} --template-file ./provision/pubsub.bicep --parameters: ./provision/pubsub.parameters.json
      - name: deploy container registry
        run: |
          az deployment group create --mode Incremental --resource-group ${{ secrets.AZURE_RG }} --template-file ./provision/registry-setup.bicep
      - name: docker push checkout app
        run: |
          az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
      - run: |
          cd src/services/checkout
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/checkout:${{ github.sha }}
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/checkout:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/checkout:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/checkout:latest
          cd ../order-processor
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/order:${{ github.sha }}
          docker tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/order:${{ github.sha }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/order:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/order:latest
