on:
  workflow_call:
name: 1. Setup Environment
jobs:
  bicep-provision-environment:
    runs-on: ubuntu-latest
    steps:
      - name: login
        uses: ./.github/workflows/login.yml
        secrets: inherit
        # Deploy Bicep file
      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          deploymentMode: Incremental
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./provision/environment.bicep
          parameters: ./provision/environment.parameters.json
          failOnStdErr: false
