on:
  workflow_call:
    inputs:
      secrets:
        azure_credentials:
          required: true
name: 0. Initialize
jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: azure_credentials
