on:
  workflow_call:
    # secrets:
    #   credentials:
    #     required: true
name: login
jobs:
  login:
    runs-on: ubuntu-latest
    steps: 
        # Log into Azure
      - uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          