on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - provision/dapr.bicep
name: Platform Deploy
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        deploymentMode: Incremental
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template:  ./provision/dapr.bicep
        parameters: 
          environment_name=containerEnv        
        failOnStdErr: false
