on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: Matrix
jobs:
  login:
    runs-on: ubuntu-latest
  initialize:
    uses: ./.github/workflows/initialize.yml
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
