on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: Matrix
jobs:
  matrix:
    runs-on: ubuntu-latest
    secrets: inherit
    steps: 
        # Log into Azure
      - uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: initialize
        uses: ./.github/workflows/initialize.yml
      - name: environment
        uses: ./.github/workflows/environment.yml
