on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: Matrix
jobs:
  initialize:
    uses: ./provision/workflows/0-initialize.yaml@main