on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: Matrix
jobs:
  login:
    runs-on: ubuntu-latest
    steps: 
        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  initialize:
    needs: login
    uses: ./.github/workflows/initialize.yml
