on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: 0. Initialize
jobs:
  call-workflow-in-local-repo:
    uses: ./provision/workflows/0-initialize.yaml