on:
  workflow_dispatch:
    branches:
      - main
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - provision/dapr.bicep
name: Matrix
jobs:
  initialize:
    uses: ./.github/workflows/initialize.yml
    with:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
